config/routes.rb
Water::Application.routes.draw do

  resources :realateditems, path: '/cat/related_items'

  resources :restrictions

  resources :helptexts
  resources :questions, only: [:index], path: 'faq'

  match '/home', to: redirect('/')
  match '/cat', to: redirect('/cat/coolers')
  mount Ckeditor::Engine => '/ckeditor'

  resources :ovodes, path: 'o-vode'

  resources :request_calls

  resources :quick_orders do
    collection do
      get 'thanks'
    end
  end

  resources :regions
  resources :banners

  resources :costs

  resources :accessories, path: '/cat/accessories'

  resources :coolers, path: '/cat/coolers'

  resources :waterbottles , path: '/price'

  resources :specoffers, path: '/skidki'

  resources :newspages

  resources :infopages, path: '' do
    collection do
      get 'list'
      get 'sitemap'
    end
  end

  resources :categories do
    collection do
      get 'mail'
    end
  end

  devise_for :users do
    get '/users/logout' => 'devise/sessions#destroy', as: 'logout'
  end
  match '/old-path', to: redirect('/new-path')
  match '/cat/coolers/item/1-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-le', to: redirect('/cat/coolers/1')
  match '/cat/coolers/item/8-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-l', to: redirect('/cat/coolers/2')
  match '/cat/coolers/item/6-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-170-ld', to: redirect('/cat/coolers/3')
  match '/cat/coolers/item/7-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-l', to: redirect('/cat/coolers/4')
  match '/cat/coolers/item/9-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-bio-family-wbf-1000', to: redirect('/cat/coolers/5')
  match '/cat/coolers/item/10-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-ylr-2-5-x-16l/hl', to: redirect('/cat/coolers/6')
  match '/cat/coolers/item/11-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-l%D1%81', to: redirect('/cat/coolers/7')
  match '/cat/coolers/item/13-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-g2-lspm', to: redirect('/cat/coolers/8')
  match '/cat/coolers/item/19-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-lf', to: redirect('/cat/coolers/9')
  match '/cat/coolers/item/20-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-lf', to: redirect('/cat/coolers/10')
  match '/cat/coolers/item/21-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-c2-lfpm', to: redirect('/cat/coolers/11')
  match '/cat/coolers/item/23-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-myl31-s-%D0%B2-black', to: redirect('/cat/coolers/12')
  match '/cat/coolers/item/24-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-tn', to: redirect('/cat/coolers/13 ')
  match '/cat/coolers/item/26-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-te', to: redirect('/cat/coolers/14')
  match '/cat/coolers/item/27-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-te', to: redirect('/cat/coolers/15')
  match '/cat/coolers/item/28-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-340-td', to: redirect('/cat/coolers/16')
  match '/cat/coolers/item/29-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-t', to: redirect('/cat/coolers/17')
  match '/cat/coolers/item/30-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-%D1%812-tpm', to: redirect('/cat/coolers/18')
  match '/cat/coolers/item/31-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-bio-family-wbf-1000s', to: redirect('/cat/coolers/19')

  root to: 'infopages#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/waterbottle.rb
class Waterbottle < ActiveRecord::Base
	has_many :costs
	mount_uploader :photo, PhotoUploader
	attr_accessible :photo, :name, :seotitle, :seodesc, :seokeywords, :title, :tabledesc, :description, :maker, :volume, :corporatedesc, :individualdesc
	def name
		self.title + " - " + self.volume.to_s
	end

	def icosts
		self.costs.where(:individual=>true)
	end
	def ccosts
  	self.costs.where(:corporate=>true)
  end

  def calprice kolvo

  end
end

app/controllers/waterbottles_controller.rb

# -*- encoding : utf-8 -*-
class WaterbottlesController < ApplicationController
  before_filter :admin_require, :except => [ :show, :index ]
  # GET /waterbottles
  # GET /waterbottles.json
  def index
    @waterbottles = Waterbottle.order("volume DESC").all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @waterbottles }
    end
  end

  # GET /waterbottles/1
  # GET /waterbottles/1.json
  def show
    @waterbottle = Waterbottle.find(params[:id])

    @title = @waterbottle.try(:seotitle)
    @seodesc = @waterbottle.try(:seodesc)
    @seokeys = @waterbottle.try(:seokeywords)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @waterbottle }
    end
  end

  # GET /waterbottles/new
  # GET /waterbottles/new.json
  def new
    @waterbottle = Waterbottle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @waterbottle }
    end
  end

  # GET /waterbottles/1/edit
  def edit
    @waterbottle = Waterbottle.find(params[:id])
  end

  # POST /waterbottles
  # POST /waterbottles.json
  def create
    @waterbottle = Waterbottle.new(params[:waterbottle])

    respond_to do |format|
      if @waterbottle.save
        format.html { redirect_to waterbottles_url, notice: 'Waterbottle was successfully created.' }
        format.json { render json: @waterbottle, status: :created, location: @waterbottle }
      else
        format.html { render action: "new" }
        format.json { render json: @waterbottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /waterbottles/1
  # PUT /waterbottles/1.json
  def update
    @waterbottle = Waterbottle.find(params[:id])

    respond_to do |format|
      if @waterbottle.update_attributes(params[:waterbottle])
        format.html { redirect_to @waterbottle, notice: 'Waterbottle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @waterbottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waterbottles/1
  # DELETE /waterbottles/1.json
  def destroy
    @waterbottle = Waterbottle.find(params[:id])
    @waterbottle.destroy

    respond_to do |format|
      format.html { redirect_to waterbottles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/waterbottles_helper.rb
module WaterbottlesHelper
end

app/views/waterbottles/_form.html.erb
<%= simple_form_for(@waterbottle) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :seotitle %>
    <%= f.input :seodesc %>
    <%= f.input :seokeywords %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :tabledesc %>
    <%= f.input :maker %>
    <%= f.input :volume %>
    <%= f.input :corporatedesc %>
    <%= f.input :individualdesc %>
    <%= f.input :photo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/waterbottles/edit.html.erb
<h1>Editing waterbottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @waterbottle %> |
<%= link_to 'Back', waterbottles_path %>

app/views/waterbottles/index.html.erb
<div class="lftclmn">
  <div class="lftclmn__bottle-types">
    <div class="lftclmn__bottle-types__big lftclmn__bottle-types_inline">
      <%= image_tag 'big_bottle.jpg' %>
      <br/>
      <a href="javascript:void(0)" onclick="$('body').scrollTo('.19_bottle'); return false;">
        19 литров
      </a>
    </div>
    <div class="lftclmn__bottle-types__middle lftclmn__bottle-types_inline">
      <%= image_tag 'middle_bottle.jpg' %>
      <br/>
      <a href="javascript:void(0)" onclick="$('body').scrollTo('.8_bottle'); return false;">
        8-6 литров
      </a>
    </div>
    <div class="lftclmn__bottle-types__small lftclmn__bottle-types_inline">
      <%= image_tag 'small_bottle.jpg' %>
      <br/>
      <a href="javascript:void(0)" onclick="$('body').scrollTo('.1_bottle'); return false;">
        1,5-0,33 литров
      </a>
    </div>
  </div>

  <% @waterbottles.each do |waterbottle| %>
    <div class ="bottle <%=waterbottle.volume.to_i%>_bottle">
      <div class="title2">
        <h1><%= waterbottle.title %>, "<%= waterbottle.maker %>" <%= waterbottle.volume%> л</h1>
      </div>
      <div class="bottle_content">
        <%- if waterbottle.ccosts.present? && waterbottle.icosts.present? %>
          <div class="bottle_content__image span2">
            <%- if waterbottle.photo.present? %>
              <%= image_tag waterbottle.photo.spec_offer.url, alt: waterbottle.name %>
            <%- end %>
          </div>

          <div class="bottle_content__table span6">
            <div class="bottle_content__table_title bottle_content__table_ctitle">
              Для КОРПОРАТИВНЫХ клиентов(Цена за 1 шт)
            </div>
            <div class="bottle_content__table_ccontent">
              <% unless waterbottle.ccosts.blank? %>
                <div class="bottle_content__table_ccontent_prices">
                  <table>
                    <tr class="table__columns-names">
                      <%- klass = 'even' -%>
                      <td class="none-background-color bottle__image__column">
                        <%= image_tag '/assets/count.png', class: 'big_bottle'%>
                      </td>
                      <% waterbottle.ccosts.each do |cost|%>
                        <%- klass = cycle('even', 'odd') -%>
                        <td class="<%= klass %>">
                          <%= cost.startcount %> - <%= cost.endcount%>
                        </td>
                      <% end %>
                      <td class="<%= klass == 'even' ? 'odd' : 'even' %>">
                        от <%= waterbottle.ccosts.last.endcount + 1 %>
                      </td>
                    </tr>

                    <tr class="table__columns-values">
                      <%- klas = 'even' -%>
                      <td class="none-background-color bottle__image__column">
                        <%= image_tag '/assets/currency.png', class: 'count_bottle'%>
                      </td>
                      <% waterbottle.ccosts.each do |cost|%>
                        <%- klas = cycle('even', 'odd') -%>
                        <td class="<%= klas %>">
                          <%= format("%.2f", cost.price) %>
                        </td>
                      <% end %>
                      <td class="<%= klas == 'even' ? 'odd' : 'even' %>">
                        договорная
                      </td>
                    </tr>

                  </table>
                </div>
                <br>
              <% end %>
            </div>
            <div class="bottle_content__table_title bottle_content__table_ititle">
              <% if waterbottle.tabledesc.blank? %>
                Для ЧАСТНЫХ клиентов(Цена за 1 шт)
              <% else %>
                <%= waterbottle.tabledesc %>
              <% end %>
            </div>
            <div class="bottle_content__table_icontent">
              <% unless waterbottle.icosts.blank? %>
                <div class="bottle_content__table_ccontent_prices">
                  <table>
                    <tr class="table__columns-names">
                      <%- clas = 'even' -%>
                      <td class="none-background-color bottle__image__column">
                        <%= image_tag '/assets/count.png', class: 'big_bottle'%>
                      </td>
                      <% waterbottle.icosts[0..-2].each do |cost|%>
                        <%- clas = cycle('odd','even') -%>
                        <td class="<%= clas %>">
                          <%= cost.startcount %> - <%= cost.endcount%>
                        </td>
                      <% end %>
                      <td class="<%= clas == 'even' ? 'odd' : 'even' %>">
                        от <%= waterbottle.icosts.last.startcount %>
                      </td>
                    </tr>

                    <tr class="table__columns-values">
                      <%- klas = 'even' -%>
                      <td class="none-background-color bottle__image__column">
                        <%= image_tag '/assets/currency.png', class: 'count_bottle'%>
                      </td>
                      <% waterbottle.icosts[0..-2].each do |cost|%>
                        <%- klas = cycle('even', 'odd') -%>
                        <td class="<%= klas %>">
                          <%= format("%.2f", cost.price) %>
                        </td>
                      <% end %>
                      <td class="<%= klas == 'even' ? 'odd' : 'even' %>">
                        <%= format("%.2f", waterbottle.icosts.last.price) %>
                      </td>
                    </tr>
                  </table>
                </div>
              <% end %>

            </div>
          </div>
          <div class="clearfix"></div>
        <%- elsif waterbottle.icosts.present? %>
          <div class="bottle_content__image2 span2">
            <%- if waterbottle.photo.present? %>
              <%= image_tag waterbottle.photo.spec_offer.url, alt: waterbottle.name %>
            <%- end %>
          </div>

          <div class="bottle_content__table span6">
            <div class="bottle_content__table_title bottle_content__table_ititle">
              <% if waterbottle.tabledesc.blank? %>
                Для ЧАСТНЫХ клиентов(Цена за 1 шт)
              <% else %>
                <%= waterbottle.tabledesc %>
              <% end %>
            </div>
            <div class="bottle_content__table_icontent">
              <% unless waterbottle.icosts.blank? %>
                <div class="bottle_content__table_ccontent_prices">
                  <table>
                    <tr class="table__columns-names">
                      <%- clas = 'even' -%>
                      <td class="none-background-color bottle__image__column">
                        <%= image_tag '/assets/count.png', class: 'big_bottle'%>
                      </td>
                      <% waterbottle.icosts[0..-2].each do |cost|%>
                        <%- clas = cycle('odd','even') -%>
                        <td class="<%= clas %>">
                          <%= cost.startcount %> - <%= cost.endcount%>
                        </td>
                      <% end %>
                      <td class="<%= clas == 'even' ? 'odd' : 'even' %>">
                        от <%= waterbottle.icosts.last.startcount %>
                      </td>
                    </tr>

                    <tr class="table__columns-values">
                      <%- klas = 'even' -%>
                      <td class="none-background-color bottle__image__column">
                        <%= image_tag '/assets/currency.png', class: 'count_bottle'%>
                      </td>
                      <% waterbottle.icosts[0..-2].each do |cost|%>
                        <%- klas = cycle('even', 'odd') -%>
                        <td class="<%= klas %>">
                          <%= format("%.2f", cost.price) %>
                        </td>
                      <% end %>
                      <td class="<%= klas == 'even' ? 'odd' : 'even' %>">
                        <%= format("%.2f", waterbottle.icosts.last.price) %>
                      </td>
                    </tr>
                  </table>
                </div>
              <% end %>

            </div>
          </div>
          <div class="clearfix"></div>
        <%- end %>
      </div>
      <% if current_user.try(:isAdmin?)   %>
          <%= link_to 'Show', waterbottle %>
          <%= link_to 'Edit', edit_waterbottle_path(waterbottle) %>
          <%= link_to 'Destroy', url_for(waterbottle), confirm: 'Are you sure?', method: :delete %>
      <% end %>
    </div>
    <div>
      <%= waterbottle.individualdesc %>
    </div>
  <% end %>

  <br />
  <% if current_user.try(:isAdmin?)   %>
    <%= link_to 'New Waterbottle', new_waterbottle_path %>
  <% end %>
</div>

<div class="rgtclmn">
  <% unless @newspages.blank? %>
    <div class="news-title"> Новости компании </div>
  <% end %>
  <div class="for_clear"></div>
  <% if @newspages[0] %>
    <div class="news-p">
      <div class="news-time"><%=@newspages[0].created_at.strftime("%d.%m.%Y") %></div>
      <%=@newspages[0].short_desc%>
      <%= link_to 'Подробнее', @newspages[0] %>
    </div>
  <% end %>

  <div class="for_clear"></div>
  <% if @newspages[1] %>
    <div class="news-p tmp">
      <div class="news-time"><%=@newspages[1].created_at.strftime("%d.%m.%Y")%></div>
      <%=@newspages[1].short_desc %>
      <%= link_to "Подробнее", @newspages[1] %>
    </div>
  <% end %>

  <div class="for_clear"></div>
  <% if @newspages[2] %>
    <div class="news-p">
      <div class="news-time"><%=@newspages[2].created_at.strftime("%d.%m.%Y")%></div>
      <%=@newspages[2].short_desc%>
      <%= link_to "Подробнее", @newspages[2] %>
    </div>
  <% end %>
  <br/>
  <div class="alllnk"> <%= link_to "Все новости", newspages_path %></div>
  <br/>
</div>

<div class="fclr"></div>

app/views/waterbottles/new.html.erb
<h1>New waterbottle</h1>

<%= render 'form' %>

<%= link_to 'Back', waterbottles_path %>

app/views/waterbottles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h1><%= @waterbottle.title %>, "<%= @waterbottle.maker %>" <%= @waterbottle.volume%> л</h1>
</div>

<% unless @waterbottle.ccosts.blank? %>
  <table class="waterb">
    <tr>
      <td rowspan="3"><%= image_tag @waterbottle.photo.spec_offer.url %></td>
      <td colspan="<%= @waterbottle.ccosts.count + 1 %>">Для КОРПОРАТИВНЫХ клиентов(Цена за 1 шт)</td>

    </tr>

    <tr>
      <% @waterbottle.ccosts.each do |cost|%>
        <td><%= cost.startcount %> - <%= cost.endcount%> шт.</td>
      <% end %>
      <td> от <%= @waterbottle.ccosts.last.endcount + 1 %>  шт.</td>

    </tr>

    <tr>
      <% @waterbottle.ccosts.each do |cost|%>
        <td><%= cost.price %> руб.</td>
      <% end %>
      <td> договорная</td>
    </tr>

  </table>

  <br>

  <div>
    <%= @waterbottle.corporatedesc %>
  </div>
  <br>
<% end %>


<table class="waterb">
  <tr>
    <td rowspan="3"><%= image_tag @waterbottle.photo.spec_offer.url %></td>
    <td colspan="<%= @waterbottle.icosts.count %>">Для ЧАСТНЫХ клиентов(Цена за 1 шт)</td>

  </tr>

  <tr>
    <% @waterbottle.icosts[0..-2].each do |cost|%>
      <td><%= cost.startcount %> - <%= cost.endcount%> шт.</td>
    <% end %>
    

  </tr>

  <tr>
    <% @waterbottle.icosts[0..-2].each do |cost|%>
      <td><%= cost.price %> руб.</td>
    <% end %>
    <td> <%= @waterbottle.icosts.last.price %> руб.</td>
  </tr>

</table>

<br>

<div>
  <%= @waterbottle.individualdesc %>
</div>

<% if current_user.try(:isAdmin?)   %>
  <p>
    <b>Seotitle:</b>
    <%= @waterbottle.seotitle %>
  </p>

  <p>
    <b>Seodesc:</b>
    <%= @waterbottle.seodesc %>
  </p>

  <p>
    <b>Seokeywords:</b>
    <%= @waterbottle.seokeywords %>
  </p>
  <%= link_to 'Edit', edit_waterbottle_path(@waterbottle) %> |
  <%= link_to 'Back', waterbottles_path %>
<% end %>