config/routes.rb
Water::Application.routes.draw do

  resources :realateditems, path: '/cat/related_items'

  resources :restrictions

  resources :helptexts
  resources :questions, only: [:index], path: 'faq'

  match '/home', to: redirect('/')
  match '/cat', to: redirect('/cat/coolers')
  mount Ckeditor::Engine => '/ckeditor'

  resources :ovodes, path: 'o-vode'

  resources :request_calls

  resources :quick_orders do
    collection do
      get 'thanks'
    end
  end

  resources :regions
  resources :banners

  resources :costs

  resources :accessories, path: '/cat/accessories'

  resources :coolers, path: '/cat/coolers'

  resources :waterbottles , path: '/price'

  resources :specoffers, path: '/skidki'

  resources :newspages

  resources :infopages, path: '' do
    collection do
      get 'list'
      get 'sitemap'
    end
  end

  resources :categories do
    collection do
      get 'mail'
    end
  end

  devise_for :users do
    get '/users/logout' => 'devise/sessions#destroy', as: 'logout'
  end
  match '/old-path', to: redirect('/new-path')
  match '/cat/coolers/item/1-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-le', to: redirect('/cat/coolers/1')
  match '/cat/coolers/item/8-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-l', to: redirect('/cat/coolers/2')
  match '/cat/coolers/item/6-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-170-ld', to: redirect('/cat/coolers/3')
  match '/cat/coolers/item/7-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-l', to: redirect('/cat/coolers/4')
  match '/cat/coolers/item/9-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-bio-family-wbf-1000', to: redirect('/cat/coolers/5')
  match '/cat/coolers/item/10-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-ylr-2-5-x-16l/hl', to: redirect('/cat/coolers/6')
  match '/cat/coolers/item/11-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-l%D1%81', to: redirect('/cat/coolers/7')
  match '/cat/coolers/item/13-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-g2-lspm', to: redirect('/cat/coolers/8')
  match '/cat/coolers/item/19-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-lf', to: redirect('/cat/coolers/9')
  match '/cat/coolers/item/20-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-lf', to: redirect('/cat/coolers/10')
  match '/cat/coolers/item/21-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-c2-lfpm', to: redirect('/cat/coolers/11')
  match '/cat/coolers/item/23-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-myl31-s-%D0%B2-black', to: redirect('/cat/coolers/12')
  match '/cat/coolers/item/24-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-tn', to: redirect('/cat/coolers/13 ')
  match '/cat/coolers/item/26-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h2-te', to: redirect('/cat/coolers/14')
  match '/cat/coolers/item/27-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-te', to: redirect('/cat/coolers/15')
  match '/cat/coolers/item/28-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ael-340-td', to: redirect('/cat/coolers/16')
  match '/cat/coolers/item/29-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-h1-t', to: redirect('/cat/coolers/17')
  match '/cat/coolers/item/30-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-ecotronic-%D1%812-tpm', to: redirect('/cat/coolers/18')
  match '/cat/coolers/item/31-%D0%BA%D1%83%D0%BB%D0%B5%D1%80-bio-family-wbf-1000s', to: redirect('/cat/coolers/19')

  root to: 'infopages#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :waterbottle
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_filter :admin_require
  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @costs }
    end
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    @cost = Cost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/new
  # GET /costs/new.json
  def new
    @cost = Cost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cost }
    end
  end

  # GET /costs/1/edit
  def edit
    @cost = Cost.find(params[:id])
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(params[:cost])

    respond_to do |format|
      if @cost.save
        format.html { redirect_to waterbottles_url, notice: 'Cost was successfully created.' }
        format.json { render json: @cost, status: :created, location: @cost }
      else
        format.html { render action: "new" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /costs/1
  # PUT /costs/1.json
  def update
    @cost = Cost.find(params[:id])

    respond_to do |format|
      if @cost.update_attributes(params[:cost])
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost = Cost.find(params[:id])
    @cost.destroy

    respond_to do |format|
      format.html { redirect_to costs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= simple_form_for(@cost) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :waterbottle %>
    <%= f.input :startcount %>
    <%= f.input :endcount %>
    <%= f.input :price %>
    <%= f.input :corporate %>
    <%= f.input :individual %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<h1>Listing costs</h1>

<table>
  <tr>
    <th>Waterbottle</th>
    <th>Startcount</th>
    <th>Endcount</th>
    <th>Price</th>
    <th>Corporate</th>
    <th>Individual</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @costs.each do |cost| %>
  <tr>
    <td><%= cost.waterbottle.name %></td>
    <td><%= cost.startcount %></td>
    <td><%= cost.endcount %></td>
    <td><%= format("%.2f", cost.price)%></td>
    <td><%= cost.corporate %></td>
    <td><%= cost.individual %></td>
    <td><%= link_to 'Show', cost %></td>
    <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
    <td><%= link_to 'Destroy', cost, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New cost</h1>

<%= render 'form' %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Waterbottle:</b>
  <%= @cost.waterbottle %>
</p>

<p>
  <b>Startcount:</b>
  <%= @cost.startcount %>
</p>

<p>
  <b>Endcount:</b>
  <%= @cost.endcount %>
</p>

<p>
  <b>Price:</b>
  <%= @cost.price %>
</p>

<p>
  <b>Corporate:</b>
  <%= @cost.corporate %>
</p>

<p>
  <b>Individual:</b>
  <%= @cost.individual %>
</p>


<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>